# Site settings
title: Sparkling Code
email: me@jonathanmoss.me
description: Your code should be so good, it sparkles.
baseurl: "http://www.sparklingcode.co"
url: "http://www.sparkingcode.co"
twitter_username: applerebel
github_username:  maclover7

# Build settings
markdown: kramdown
exclude: ["Gemfile", "Gemfile.lock"]
